plugins {
	id 'java-library'
	id 'jacoco'
}

group = 'io.github.johnsobrepena.ideasparx'
version = '1.0.0'

repositories {
	mavenCentral()
}

dependencies {
}

testing {
	suites {
		test {
			useJUnitJupiter(libs.versions.junitJupiter.get())
		}
	}
}

jacoco {
	toolVersion = "0.8.15"
}

jacocoTestReport {
	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.90
			}
		}
	}
}

tasks.named("test", Test){
	finalizedBy jacocoTestReport, jacocoTestCoverageVerification
}

tasks.named("check") {
	dependsOn jacocoTestCoverageVerification
}


java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}
